### ISSUE TITLE
Works just when ENVIROMENT=dev

### ISSUE THREAD

**Issue by samuel-clara** [jalendport/craft-lockout#4]
Would love to use this plugin but it seems that the plugin works just when the .env variable ENVIRONMENT=dev.
When setting this to staging or production non-admin users are not locked out.

Running Craft CMS 3.7.54

**Comment by jalendport** [comment]
So this is probably on me for not documenting this better (or at all tbh 😬), but because Project Config on a Staging or Production environment will prevent you from editing plugin settings, Lockout actually stores the enable/disable value in a custom database table, and it's stored per environment. So if you enable it in dev, it will only apply to dev. If you want to enable it on staging or production, you will need to add the widget to the dashboard and then you can toggle the value from there.

I set it up this way so that it wouldn't require a commit/deployment to toggle Lockout, and pushing DBs up or down wouldn't cause unintended issues either. Having it be a manual process to toggle per environment just seemed to make the most sense... Hopefully that clarifies things?
